出力結果は: `1`.

`resolve` の2度目の呼び出しは無視されます。なぜなら `reject/resolve` の初回の呼び出しのみが考慮されるためです。さらなる呼び出しは無視されます。
